export interface ToolSEOData {
  slug: string;
  name: string;
  title: string;
  metaDescription: string;
  mainKeyword: string;
  keywords: string[];
  searchQueries: string[];
}

export const TOOL_SEO_MAP: Record<string, ToolSEOData> = {
  'image-downloader': {
    slug: 'image-downloader',
    name: 'YouTube Image Downloader',
    title: 'YouTube Image Downloader - HD Channel Banners, Avatars & Logos',
    metaDescription: 'Download YouTube channel banner images in 2560x1440 HD, full-size 800x800 profile pictures (PFP), and channel logos for free. Instant HD image extraction.',
    mainKeyword: 'YouTube Image Downloader',
    keywords: [
      'how to download youtube channel banner image hd',
      'youtube profile picture downloader high resolution',
      'youtube thumbnail and banner downloader free',
      'how to download youtube banner image on mobile',
      'youtube banner image downloader tool online',
      'extract images from youtube video online free',
      'youtube logo and channel art downloader',
      'youtube community post image downloader hd',
      'how to save high quality youtube channel banner',
      'best youtube image finder and downloader',
      'youtube pfp viewer and downloader full size',
      'how to get youtube channel art image url',
      'download youtube video thumbnail as image',
      'youtube header image downloader free online',
      'how to save youtube avatar image full hd',
      'YouTube Image Downloader',
      'channel art downloader',
      'youtube pfp saver',
    ],
    searchQueries: [
      'how to download youtube channel banner image hd',
      'youtube profile picture downloader high resolution',
      'youtube thumbnail and banner downloader free',
      'how to download youtube banner image on mobile',
      'youtube banner image downloader tool online',
      'extract images from youtube video online free',
      'youtube logo and channel art downloader',
      'youtube community post image downloader hd',
      'how to save high quality youtube channel banner',
      'best youtube image finder and downloader',
      'youtube pfp viewer and downloader full size',
      'how to get youtube channel art image url',
      'download youtube video thumbnail as image',
      'youtube header image downloader free online',
      'how to save youtube avatar image full hd',
    ],
  },
  'hidden-video-finder': {
    slug: 'hidden-video-finder',
    name: 'YouTube Unlisted & Hidden Video Finder',
    title: 'YouTube Unlisted & Hidden Video Finder - Search & Discover Unlisted Videos',
    metaDescription: 'Find unlisted and hidden YouTube videos on any channel or playlist. Discover secret playlist items, detect locked private video slots, and search unlisted links free.',
    mainKeyword: 'YouTube Unlisted & Hidden Video Finder',
    keywords: [
      'how to find unlisted youtube videos without link',
      'free unlisted youtube video finder tool online',
      'how to search unlisted videos on youtube',
      'find hidden youtube videos of a channel',
      'youtube unlisted video search engine free',
      'how to watch unlisted videos on youtube 2026',
      'find private and unlisted youtube videos',
      'how to get url of unlisted youtube video',
      'youtube playlist unlisted video finder tool',
      'how to discover hidden videos on youtube',
      'search unlisted youtube videos by keyword',
      'can you find unlisted videos on youtube channel',
      'best unlisted youtube video search engine',
      'how to see unlisted youtube videos on mobile',
      'site to search unlisted youtube videos free',
      'YouTube Unlisted & Hidden Video Finder',
      'hidden video search tool',
    ],
    searchQueries: [
      'how to find unlisted youtube videos without link',
      'free unlisted youtube video finder tool online',
      'how to search unlisted videos on youtube',
      'find hidden youtube videos of a channel',
      'youtube unlisted video search engine free',
      'how to watch unlisted videos on youtube 2026',
      'find private and unlisted youtube videos',
      'how to get url of unlisted youtube video',
      'youtube playlist unlisted video finder tool',
      'how to discover hidden videos on youtube',
      'search unlisted youtube videos by keyword',
      'can you find unlisted videos on youtube channel',
      'best unlisted youtube video search engine',
      'how to see unlisted youtube videos on mobile',
      'site to search unlisted youtube videos free',
    ],
  },
  'earnings-calculator': {
    slug: 'earnings-calculator',
    name: 'YouTube Earnings Calculator',
    title: 'YouTube Earnings Calculator - Estimate Monetization Revenue & RPM',
    metaDescription: 'Calculate how much YouTube pays for 1K to 1M views. Estimate channel earnings, Shorts monetization revenue, RPM & CPM by niche, daily income, and net worth.',
    mainKeyword: 'YouTube Earnings Calculator',
    keywords: [
      'how much youtube pays for 1 million views calculator',
      'youtube money calculator by channel url free',
      'youtube shorts monetization earnings calculator online',
      'calculate youtube earnings based on views and cpm',
      'free youtube income calculator tool for creators',
      'how much money per 1000 views on youtube',
      'youtube revenue estimator by channel link',
      'youtube channel net worth calculator tool',
      'estimate youtube earnings per video free',
      'youtube adsense money calculator by niche',
      'youtube monetization RPM calculator online',
      'how to calculate youtube video daily revenue',
      'free youtube money calculator for shorts views',
      'calculate estimated monthly earnings from youtube',
      'youtube income checker by sub count and views',
      'YouTube Earnings Calculator',
      'youtube money estimator',
    ],
    searchQueries: [
      'how much youtube pays for 1 million views calculator',
      'youtube money calculator by channel url free',
      'youtube shorts monetization earnings calculator online',
      'calculate youtube earnings based on views and cpm',
      'free youtube income calculator tool for creators',
      'how much money per 1000 views on youtube',
      'youtube revenue estimator by channel link',
      'youtube channel net worth calculator tool',
      'estimate youtube earnings per video free',
      'youtube adsense money calculator by niche',
      'youtube monetization RPM calculator online',
      'how to calculate youtube video daily revenue',
      'free youtube money calculator for shorts views',
      'calculate estimated monthly earnings from youtube',
      'youtube income checker by sub count and views',
    ],
  },
  'shadowban-detector': {
    slug: 'shadowban-detector',
    name: 'YouTube Shadowban Detector',
    title: 'YouTube Shadowban Detector - Channel & Shorts Diagnostic Test 2026',
    metaDescription: 'Check if your YouTube channel or Shorts are shadowbanned. Test public search indexing, sudden view drops, video visibility, and comment shadowbans free online.',
    mainKeyword: 'YouTube Shadowban Detector',
    keywords: [
      'how to check if youtube channel is shadowbanned',
      'free youtube shadowban checker tool online',
      'why are my youtube views suddenly dropping',
      'am i shadowbanned on youtube check tool',
      'how to fix youtube shadowban on shorts',
      'youtube comment shadowban checker online free',
      'how to know if your youtube video is restricted',
      'test youtube channel shadowban status free',
      'youtube algorithm penalty vs shadowban checker',
      'how to unshadowban youtube channel fast',
      'youtube shadowban test by channel link',
      'why my youtube videos are not showing in search results',
      'check if my youtube comment is shadowbanned',
      'youtube account shadowban checker tool 2026',
      'how to check if youtube shorts are shadowbanned',
      'YouTube Shadowban Detector',
      'youtube shadowban checker',
    ],
    searchQueries: [
      'how to check if youtube channel is shadowbanned',
      'free youtube shadowban checker tool online',
      'why are my youtube views suddenly dropping',
      'am i shadowbanned on youtube check tool',
      'how to fix youtube shadowban on shorts',
      'youtube comment shadowban checker online free',
      'how to know if your youtube video is restricted',
      'test youtube channel shadowban status free',
      'youtube algorithm penalty vs shadowban checker',
      'how to unshadowban youtube channel fast',
      'youtube shadowban test by channel link',
      'why my youtube videos are not showing in search results',
      'check if my youtube comment is shadowbanned',
      'youtube account shadowban checker tool 2026',
      'how to check if youtube shorts are shadowbanned',
    ],
  },
  'thumbnail-downloader': {
    slug: 'thumbnail-downloader',
    name: 'YouTube Thumbnail Downloader',
    title: 'YouTube Thumbnail Downloader - Full HD 1080p, 4K & Shorts Image Saver',
    metaDescription: 'Download YouTube video and Shorts thumbnails in Full HD 1080p, 4K max resolution, and HQ formats. Free thumbnail grabber without watermark for any YouTube link.',
    mainKeyword: 'YouTube Thumbnail Downloader',
    keywords: [
      'download youtube video thumbnail full hd 1080p',
      'free youtube thumbnail downloader 4k quality',
      'how to download thumbnail from youtube video',
      'youtube thumbnail grabber tool online free',
      'save youtube video thumbnail picture hd',
      'youtube thumbnail downloader high resolution online',
      'extract thumbnail image from youtube video link',
      'download youtube shorts thumbnail high quality',
      'best youtube thumbnail viewer and saver',
      'how to download youtube thumbnail on android',
      'get high quality youtube thumbnail image online',
      'youtube video max resolution thumbnail downloader',
      'free youtube thumbnail extractor HD quality',
      'download youtube thumbnail image without watermark',
      'save thumbnail from youtube link fast',
      'YouTube Thumbnail Downloader',
      'youtube thumbnail grabber',
    ],
    searchQueries: [
      'download youtube video thumbnail full hd 1080p',
      'free youtube thumbnail downloader 4k quality',
      'how to download thumbnail from youtube video',
      'youtube thumbnail grabber tool online free',
      'save youtube video thumbnail picture hd',
      'youtube thumbnail downloader high resolution online',
      'extract thumbnail image from youtube video link',
      'download youtube shorts thumbnail high quality',
      'best youtube thumbnail viewer and saver',
      'how to download youtube thumbnail on android',
      'get high quality youtube thumbnail image online',
      'youtube video max resolution thumbnail downloader',
      'free youtube thumbnail extractor HD quality',
      'download youtube thumbnail image without watermark',
      'save thumbnail from youtube link fast',
    ],
  },
  'tag-extractor': {
    slug: 'tag-extractor',
    name: 'YouTube Tag Extractor',
    title: 'YouTube Tag Extractor - Copy Hidden Video Tags & SEO Keywords',
    metaDescription: 'Extract, inspect, and copy hidden SEO tags and keywords from any YouTube video or Shorts. Find competitor tags and rank higher with our free YouTube tag grabber.',
    mainKeyword: 'YouTube Tag Extractor',
    keywords: [
      'how to see tags on youtube video free',
      'youtube tag extractor tool online free',
      'copy competitor youtube video tags online',
      'extract tags from any youtube video link',
      'best youtube keyword and tag finder free',
      'how to find hidden tags in youtube videos',
      'youtube video tag grabber extension online',
      'extract tags and keywords from youtube shorts',
      'free youtube seo tag generator and extractor',
      'extract youtube tags for video ranking',
      'how to extract channel tags from youtube',
      'get youtube video tags for high views',
      'copy youtube video tags with one click',
      'online tool to see youtube video tags',
      'youtube tag viewer and copier free',
      'YouTube Tag Extractor',
      'copy youtube tags',
    ],
    searchQueries: [
      'how to see tags on youtube video free',
      'youtube tag extractor tool online free',
      'copy competitor youtube video tags online',
      'extract tags from any youtube video link',
      'best youtube keyword and tag finder free',
      'how to find hidden tags in youtube videos',
      'youtube video tag grabber extension online',
      'extract tags and keywords from youtube shorts',
      'free youtube seo tag generator and extractor',
      'extract youtube tags for video ranking',
      'how to extract channel tags from youtube',
      'get youtube video tags for high views',
      'copy youtube video tags with one click',
      'online tool to see youtube video tags',
      'youtube tag viewer and copier free',
    ],
  },
  'data-viewer': {
    slug: 'data-viewer',
    name: 'YouTube Data Viewer',
    title: 'YouTube Data Viewer - Inspect Video Metadata, Exact Upload Time & Stats',
    metaDescription: 'Free YouTube data viewer and analytics inspector. Check exact video upload timestamp, channel creation date, hidden tags, duration, and full metadata by link.',
    mainKeyword: 'YouTube Data Viewer',
    keywords: [
      'free youtube data viewer tool online',
      'analyze youtube channel statistics free',
      'inspect youtube video metadata and details',
      'youtube video publish date and time checker',
      'youtube channel creation date viewer online',
      'get full youtube video metadata using link',
      'youtube search data and analytics tool',
      'free youtube video info grabber online',
      'view hidden youtube channel metadata',
      'online tool to inspect youtube video data',
      'youtube video upload time checker tool',
      'check exact upload time of youtube video',
      'youtube video analytics and data inspector',
      'free tool to view youtube video info',
      'youtube metadata extractor online free',
      'YouTube Data Viewer',
      'youtube metadata viewer',
    ],
    searchQueries: [
      'free youtube data viewer tool online',
      'analyze youtube channel statistics free',
      'inspect youtube video metadata and details',
      'youtube video publish date and time checker',
      'youtube channel creation date viewer online',
      'get full youtube video metadata using link',
      'youtube search data and analytics tool',
      'free youtube video info grabber online',
      'view hidden youtube channel metadata',
      'online tool to inspect youtube video data',
      'youtube video upload time checker tool',
      'check exact upload time of youtube video',
      'youtube video analytics and data inspector',
      'free tool to view youtube video info',
      'youtube metadata extractor online free',
    ],
  },
  'comment-viewer': {
    slug: 'comment-viewer',
    name: 'YouTube Comment Viewer',
    title: 'YouTube Comment Viewer - Search, Filter & Read Video Comments',
    metaDescription: 'Search specific words in YouTube comments, view top/latest replies, filter by username, and inspect pinned comments without logging into YouTube or installing an app.',
    mainKeyword: 'YouTube Comment Viewer',
    keywords: [
      'how to search comments on youtube video',
      'free youtube comment viewer and search tool',
      'view all comments on a youtube video online',
      'search specific word in youtube comments',
      'youtube comment history viewer by video url',
      'filter comments on youtube video online free',
      'view top and latest youtube video comments',
      'youtube comment finder tool without app',
      'how to read disabled comments on youtube',
      'view pinned comments on youtube video free',
      'youtube comment export and viewer online',
      'search youtube comments by username free',
      'online youtube comment reader and analyzer',
      'find user comments on youtube video',
      'view hidden or held for review youtube comments',
      'YouTube Comment Viewer',
      'youtube comment search',
    ],
    searchQueries: [
      'how to search comments on youtube video',
      'free youtube comment viewer and search tool',
      'view all comments on a youtube video online',
      'search specific word in youtube comments',
      'youtube comment history viewer by video url',
      'filter comments on youtube video online free',
      'view top and latest youtube video comments',
      'youtube comment finder tool without app',
      'how to read disabled comments on youtube',
      'view pinned comments on youtube video free',
      'youtube comment export and viewer online',
      'search youtube comments by username free',
      'online youtube comment reader and analyzer',
      'find user comments on youtube video',
      'view hidden or held for review youtube comments',
    ],
  },
  'random-comment-picker': {
    slug: 'random-comment-picker',
    name: 'YouTube Random Comment Picker',
    title: 'YouTube Random Comment Picker - Free Fair Giveaway Winner Generator',
    metaDescription: 'Pick random giveaway winners from YouTube video comments and Shorts. Filter duplicate users, search specific keywords, and choose fair winners with 100% transparency.',
    mainKeyword: 'YouTube Random Comment Picker',
    keywords: [
      'free youtube random comment picker for giveaway',
      'youtube comment picker pick a winner free',
      'random youtube comment picker without duplicate users',
      'free online giveaway picker for youtube comments',
      'pick winner from youtube video comments automatically',
      'youtube giveaway comment picker tool online',
      'random youtube comment picker for shorts',
      'pick random comment from youtube video free',
      'fair youtube giveaway winner picker tool',
      'youtube comment selector for contest free',
      'comment picker youtube free filter duplicate names',
      'pick multiple winners from youtube comments',
      'youtube contest winner picker generator free',
      'best random comment picker for youtube giveaways',
      'online tool to pick youtube comment winner',
      'YouTube Random Comment Picker',
      'youtube giveaway winner picker',
    ],
    searchQueries: [
      'free youtube random comment picker for giveaway',
      'youtube comment picker pick a winner free',
      'random youtube comment picker without duplicate users',
      'free online giveaway picker for youtube comments',
      'pick winner from youtube video comments automatically',
      'youtube giveaway comment picker tool online',
      'random youtube comment picker for shorts',
      'pick random comment from youtube video free',
      'fair youtube giveaway winner picker tool',
      'youtube comment selector for contest free',
      'comment picker youtube free filter duplicate names',
      'pick multiple winners from youtube comments',
      'youtube contest winner picker generator free',
      'best random comment picker for youtube giveaways',
      'online tool to pick youtube comment winner',
    ],
  },
  'dislike-checker': {
    slug: 'dislike-checker',
    name: 'YouTube Dislike & Sentiment Checker',
    title: 'YouTube Dislike & Sentiment Checker - Return Hidden Dislikes 2026',
    metaDescription: 'Check hidden YouTube video dislikes, like-to-dislike ratio, approval rating, and audience sentiment analysis online. Return YouTube dislike count free without extensions.',
    mainKeyword: 'YouTube Dislike & Sentiment Checker',
    keywords: [
      'how to see dislikes on youtube video 2026',
      'free youtube dislike counter tool online',
      'check youtube video dislikes and likes ratio',
      'return youtube dislike viewer tool free',
      'see hidden dislikes on youtube video online',
      'youtube audience sentiment analyzer tool',
      'check youtube video like vs dislike count',
      'how to bring back youtube dislikes online',
      'free youtube dislike checker extension tool',
      'analyze youtube video audience sentiment free',
      'check youtube video audience positive vs negative feedback',
      'how to reveal dislikes on any youtube video',
      'youtube dislike count viewer web tool',
      'view real time youtube video dislikes',
      'online youtube video sentiment analysis tool',
      'YouTube Dislike & Sentiment Checker',
      'return youtube dislike',
    ],
    searchQueries: [
      'how to see dislikes on youtube video 2026',
      'free youtube dislike counter tool online',
      'check youtube video dislikes and likes ratio',
      'return youtube dislike viewer tool free',
      'see hidden dislikes on youtube video online',
      'youtube audience sentiment analyzer tool',
      'check youtube video like vs dislike count',
      'how to bring back youtube dislikes online',
      'free youtube dislike checker extension tool',
      'analyze youtube video audience sentiment free',
      'check youtube video audience positive vs negative feedback',
      'how to reveal dislikes on any youtube video',
      'youtube dislike count viewer web tool',
      'view real time youtube video dislikes',
      'online youtube video sentiment analysis tool',
    ],
  },
  'description-viewer': {
    slug: 'description-viewer',
    name: 'YouTube Description Extractor & Viewer',
    title: 'YouTube Description Extractor & Viewer - Copy Text, Timestamps & Links',
    metaDescription: 'Extract and copy formatted YouTube video descriptions. Discover timestamps, chapters, external links, hashtags, and character counts from any video or Shorts link.',
    mainKeyword: 'YouTube Description Extractor & Viewer',
    keywords: [
      'extract description from youtube video online free',
      'youtube video description viewer tool',
      'copy youtube description text with timestamps',
      'free youtube description grabber online',
      'extract links from youtube video description',
      'how to download youtube video description text',
      'youtube description extractor for shorts',
      'best youtube video description viewer',
      'copy full description of youtube video online',
      'youtube description copier tool free',
      'extract tags and description from youtube link',
      'read full youtube video description online',
      'copy youtube description text formatted',
      'youtube description scraper online free',
      'extract youtube channel description text free',
      'YouTube Description Extractor & Viewer',
      'youtube description grabber',
    ],
    searchQueries: [
      'extract description from youtube video online free',
      'youtube video description viewer tool',
      'copy youtube description text with timestamps',
      'free youtube description grabber online',
      'extract links from youtube video description',
      'how to download youtube video description text',
      'youtube description extractor for shorts',
      'best youtube video description viewer',
      'copy full description of youtube video online',
      'youtube description copier tool free',
      'extract tags and description from youtube link',
      'read full youtube video description online',
      'copy youtube description text formatted',
      'youtube description scraper online free',
      'extract youtube channel description text free',
    ],
  },
  'private-viewer': {
    slug: 'private-viewer',
    name: 'Private YouTube Viewer (Anonymous Mode)',
    title: 'Private YouTube Viewer (Anonymous Mode) - Watch Without History & Tracking',
    metaDescription: 'Watch YouTube videos privately and anonymously without login, tracking cookies, or saving to Google watch history. Clean, distraction-free incognito video player.',
    mainKeyword: 'Private YouTube Viewer (Anonymous Mode)',
    keywords: [
      'watch youtube videos anonymously without history',
      'watch youtube without login or tracking',
      'private youtube video player web tool',
      'how to watch youtube videos privately online',
      'youtube incognito player web tool free',
      'watch youtube videos without sign in free',
      'block ads and watch youtube anonymously',
      'view youtube videos without saving to history',
      'anonymous youtube viewer without account',
      'private youtube search and watch tool online',
      'watch youtube video untracked free online',
      'how to view youtube videos incognito mode',
      'web based private youtube video player',
      'bypass youtube sign in to watch videos',
      'watch youtube video anonymously online player',
      'Private YouTube Viewer (Anonymous Mode)',
      'incognito youtube player',
    ],
    searchQueries: [
      'watch youtube videos anonymously without history',
      'watch youtube without login or tracking',
      'private youtube video player web tool',
      'how to watch youtube videos privately online',
      'youtube incognito player web tool free',
      'watch youtube videos without sign in free',
      'block ads and watch youtube anonymously',
      'view youtube videos without saving to history',
      'anonymous youtube viewer without account',
      'private youtube search and watch tool online',
      'watch youtube video untracked free online',
      'how to view youtube videos incognito mode',
      'web based private youtube video player',
      'bypass youtube sign in to watch videos',
      'watch youtube video anonymously online player',
    ],
  },
  'monetization-checker': {
    slug: 'monetization-checker',
    name: 'YouTube Monetization Checker',
    title: 'YouTube Monetization Checker - Check Channel Status & Signals Free 2026',
    metaDescription: 'Free YouTube monetization checker online. Check if any YouTube channel or video is monetized, inspect ad formats, calculate estimated RPM/CPM, and verify YPP signals without login.',
    mainKeyword: 'YouTube Monetization Checker',
    keywords: [
      'free youtube monetization checker online',
      'how to check if youtube channel is monetized',
      'youtube channel monetization status checker tool',
      'check youtube video monetization eligibility free',
      'how to know if a youtube channel is making money',
      'youtube channel monetization checker by url',
      'test youtube channel monetization online free',
      'youtube monetization RPM and CPM checker',
      'how to check youtube channel monetization without logging in',
      'best youtube monetization eligibility checker 2026',
      'YouTube Monetization Checker',
      'youtube ypp status checker',
      'check monetization online',
    ],
    searchQueries: [
      'free youtube monetization checker online',
      'how to check if youtube channel is monetized',
      'youtube channel monetization status checker tool',
      'check youtube video monetization eligibility free',
      'how to know if a youtube channel is making money',
      'youtube channel monetization checker by url',
      'test youtube channel monetization online free',
      'youtube monetization RPM and CPM checker',
      'how to check youtube channel monetization without logging in',
      'best youtube monetization eligibility checker 2026',
    ],
  },
  'channel-id-finder': {
    slug: 'channel-id-finder',
    name: 'YouTube Channel ID Finder',
    title: 'YouTube Channel ID Finder - Find & Convert 24-Character Channel IDs',
    metaDescription: 'Find and convert YouTube channel IDs from URLs, handles (@username), custom links, or video URLs. Copy canonical UC channel IDs instantly for API integration and SEO.',
    mainKeyword: 'YouTube Channel ID Finder',
    keywords: [
      'how to find youtube channel id from url',
      'free youtube channel id finder tool online',
      'find youtube channel id by username or link',
      'how to get youtube channel id on mobile browser',
      'how to check youtube channel id for API',
      'convert youtube custom url to channel id online',
      'find youtube channel id using page source code',
      'best youtube channel id finder extension free',
      'how to find hidden youtube channel id online',
      'get youtube channel id from video url free',
      'YouTube Channel ID Finder',
      'find uc channel id',
      'convert youtube handle to id',
    ],
    searchQueries: [
      'how to find youtube channel id from url',
      'free youtube channel id finder tool online',
      'find youtube channel id by username or link',
      'how to get youtube channel id on mobile browser',
      'how to check youtube channel id for API',
      'convert youtube custom url to channel id online',
      'find youtube channel id using page source code',
      'best youtube channel id finder extension free',
      'how to find hidden youtube channel id online',
      'get youtube channel id from video url free',
    ],
  },
};
